jobs:
  include:
    - language: java
      jdk:
        - openjdk8
        - openjdk11  # TODO: Check why this is not triggered!
      services:
        - docker
      before_install:
        - sudo apt install jq
      script:
        - cd bunsen
        - mvn --no-transfer-progress clean install
        - cd ../pipelines
        - mvn --no-transfer-progress clean install
        - export ROOT_PATH="${TRAVIS_BUILD_DIR}"
        - ../e2e-tests/batch-mode-tests.sh
      env:
        global:
          - CODECOV_TOKEN='c1a56ea5-6142-4108-a721-9e0e2e2a8083'
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - language: python
      python:  "3.8"
      script:
        - cd dwh; ./validate_indicators.sh
