"""Manages uploading of FHIR resources."""

import bundle
import fhir_hook
import log_mixin


class Uploader(log_mixin.LoggingMixin):
  """Uploads FHIR resources to either OpenMRS or any other FHIR Server."""

  def __init__(self, hook: fhir_hook.BaseHook):
    self.fhir_hook = hook

  def _upload_resource(self, **kwargs):
    """Used to POST when OpenMRS is the target sink."""

    self.fhir_hook.post_data(**kwargs)
    return self.fhir_hook.response['id']

  def upload_openmrs_bundle(self, each_bundle: bundle.Bundle):
    """Uploads FHIR Bundle to OpenMRS via Patients, Encounters, Observations.

    As the OpenMRS FHIR Module does not support uploading Bundle transactions,
    the Bundle is uploaded in 3 steps. First the Patient resource is uploaded,
    then the encounters, then the observations. Before uploading each resource,
    we have to manipulate the JSON for that resource into a form OpenMRS will
    accept.

    As OpenMRS does not support PUT requests, each time we POST a resource, a
    new ID for that resource is generated. This means we need to track the new
    id for each resource. Some resources depend on the other resources' new id.
    For example, before POSTing Encounter resource, we need to update it with
    the new Patient id generated by OpenMRS for the Encounter upload to work.

    Args:
     each_bundle: a Bundle object
    """

    try:
      self.logger.info('Uploading %s' % each_bundle.file_name)

      each_bundle.openmrs_patient.openmrs_convert()
      each_bundle.openmrs_patient.new_id = self._upload_resource(
          resource='Patient', data=each_bundle.openmrs_patient.json)

      self.logger.debug('New Patient ID is %s' %
                        each_bundle.openmrs_patient.new_id)

      for openmrs_encounter in each_bundle.openmrs_encounters:
        openmrs_encounter.openmrs_convert(each_bundle.openmrs_patient.new_id)
        openmrs_encounter.new_id = self._upload_resource(
            resource='Encounter', data=openmrs_encounter.json)

      for openmrs_observation in each_bundle.openmrs_observations:
        openmrs_observation.openmrs_convert(each_bundle.openmrs_patient.new_id,
                                            each_bundle.openmrs_encounters)
        openmrs_observation.new_id = self._upload_resource(
            resource='Observation', data=openmrs_observation.json)

      self.logger.info('Successfully uploaded %s' % each_bundle.file_name)

    except ValueError:
      self.logger.error('Error uploading %s' % each_bundle.file_name)

  def upload_bundle(self, each_bundle: bundle.Bundle):
    """Upload bundle to a FHIR Server via a POST request."""

    try:
      self.logger.info('Uploading %s' % each_bundle.file_name)
      self.fhir_hook.post_data(data=each_bundle.json)
      self.logger.info('Successfully uploaded %s' % each_bundle.file_name)

    except ValueError:
      self.logger.error('Error uploading %s' % each_bundle.file_name)
