# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Build for fhir-analytics/openmrs-reference-application-extended:latest image


# The nightly version has the FHIR 1.2.2 and OCL modules and is based on 
# Reference-app v2.14-SNAPSHOT. latest` tag does not as its based on v2.13
# TODO: Change to `latest` once 2.14 is released. 
FROM openmrs/openmrs-reference-application-distro:nightly

RUN apt-get clean && apt-get update && apt-get install -y dialog apt-utils

RUN apt-get install -y locales

# Added to avoid intermittent error:
# “Theme ‘green’: No message found under code ‘favicon’ for locale ‘en’.”
# See: https://talk.openmrs.org/t/theme-green-no-message-found-under-code-favicon-for-locale-en-gb/30836
RUN locale-gen 

RUN curl https://addons.openmrs.org/api/v1/addon/org.openmrs.module.atomfeed/1.0.13/download --create-dirs -o /usr/local/tomcat/.OpenMRS/modules/atomfeed-1.0.13.omod

CMD ["/usr/local/tomcat/startup.sh"]