# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3'

services:
  mongo-plir:
    restart: "always"
    container_name: openhim-mongo-plir
    expose: 
      - "27017"
    image: mongo:3.4
    healthcheck:
      test: "exit 0"
    
  core-plir:
    restart: "always"
    container_name: openhim-core-plir
    image: jembi/openhim-core:latest
    environment:
      - mongo_url=mongodb://mongo-plir/openhim
      - mongo_atnaUrl=mongodb://mongo-plir/openhim
    ports:
      - "5001:5001"
      - "8093:8080"
    expose :
      - "5000"
      - "5050"
      - "5051"
      - "5052"
      - "7788"
    healthcheck:
      test: "exit 0"   
    depends_on:
      - mongo-plir
  
  console-plir:
    restart: "always"
    container_name: openhim-console-plir
    image: jembi/openhim-console:latest
    ports:
        - "9000:80"  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      timeout: 20s    
    volumes:
      - ../utils/openhim-default.json:/usr/share/nginx/html/config/default.json
    