# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '2.4'
services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    container_name: openmrs-fhir-mysql-empty
    healthcheck:
      test: "exit 0"
    environment:
      - MYSQL_DATABASE=openmrs
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
      - MYSQL_ROOT_HOST=%    # Allow docker containers to connect to mysql
    volumes:
      - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf  # mysql config preconfigured to allow binlog/debezium
      - ./dbdump:/docker-entrypoint-initdb.d # executes sql files in alphabetical order


  openmrs:
    restart: "always"
    image:  openmrs/openmrs-reference-application-distro:latest
    container_name: openmrs-ocl-load
    depends_on:
      - mysql
    ports:
      - "8099:8080"
    healthcheck:
      test: "exit 0"
    environment:
      DB_DATABASE: 'openmrs'
      DB_HOST: openmrs-fhir-mysql-empty
      DB_USERNAME: 'mysqluser'
      DB_PASSWORD: 'mysqlpw'
      DB_CREATE_TABLES: 'false'
      DB_AUTO_UPDATE: 'false'
      MODULE_WEB_ADMIN: 'true'
    volumes:
      # OpenMRS loads dictionary mounted at this location on startup
      - ./extras/20210827_140605.zip:/usr/local/tomcat/.OpenMRS/ocl/configuration/loadAtStartup/20210827_140605.zip
