#
# Copyright 2020-2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# These are default application parameters read as a DataProperties instance.
# To override these, the user can provide another file in a /config sub-dir of
# where the Spring Boot application is run or use other methods like env. vars.

data:
  fhirServerUrl: "http://localhost:8092/fhir"
  dbConfig: "../../utils/hapi-postgres-config_local.json"
  dwhRootPrefix: "/tmp/controller_DWH"
  # The schedule format is similar to Spring's CronExpression, i.e.,
  # "second minute hour day-of-the-month month day-of-the-week", e.g.,
  # "0 0 * * * *" means top of every hour;
  # "*/30 * * * * *" means in the middle of each minute;
  # Note a too frequent run might be too resource intensive.
  incrementalSchedule: "0 0 * * * *"
  # Comma separated list of resources to fetch/monitor.
  resourceList: "Patient,Encounter,Observation"




